import { freezeEquipmentData } from './EquipmentData.js';
export const EQUIPMENT_FAMILY_PROFILES = freezeEquipmentData([
  {
    id: 'field-cutter',
    label: '현장 절단검',
    slot: 'weapon',
    handUsage: 'oneHand',
    combatRole: 'cut-and-disable',
    compatibleOffHandFamilies: ['field-shield'],
    twoHandCompatibleOffHandFamilies: [],
    fieldCapabilities: ['cable-cut', 'light-plate-cut', 'light-machine-disable'],
    enchantable: true,
    movesetBindings: [
      { offHandFamilyId: 'field-shield', movesetId: 'cutter-shield-standard' },
      { offHandFamilyId: null, movesetId: 'cutter-standard' },
    ],
  },
  {
    id: 'field-shield',
    label: '현장 방호판',
    slot: 'shield',
    handUsage: 'oneHand',
    combatRole: 'guard-and-brace',
    compatibleMainFamilies: ['field-cutter'],
    fieldCapabilities: ['debris-guard', 'pressure-block', 'brace'],
    enchantable: false,
  },
  {
    id: 'helmet',
    label: '작업 투구',
    slot: 'helmet',
    handUsage: 'none',
    combatRole: 'protection',
    fieldCapabilities: [],
    enchantable: false,
  },
  {
    id: 'body-armor',
    label: '작업 몸통 보호구',
    slot: 'bodyArmor',
    handUsage: 'none',
    combatRole: 'protection',
    fieldCapabilities: [],
    enchantable: false,
  },
  {
    id: 'boots',
    label: '작업화',
    slot: 'boots',
    handUsage: 'none',
    combatRole: 'protection',
    fieldCapabilities: [],
    enchantable: false,
  },
  {
    id: 'tool',
    label: '현장 도구',
    slot: 'tool',
    handUsage: 'none',
    combatRole: 'field-work',
    fieldCapabilities: ['illuminate'],
    enchantable: false,
  },
]);
