import { freezeEquipmentData } from './EquipmentData.js';
export const EQUIPMENT_ITEM_PROFILES = freezeEquipmentData([
  {
    id: 'field-cutter-balanced',
    familyId: 'field-cutter',
    label: '속공형 현장 절단검',
    shortLabel: '속공형',
    description: '짧은 frame · 짧은 거리 · 낮은 경직',
    goldCost: 0,
    trainingMarkRequirement: 0,
    visualProfile: {
      kind: 'field-cutter',
      source: 'shared-player-weapon',
      materialId: 'raw-steel',
    },
    origin: {
      kind: 'starter',
    },
    modifiers: {
      combatTiming: {
        startupScale: 0.82,
        recoveryScale: 0.84,
      },
      attack: {
        damageScale: 0.9,
        rangeScale: 0.92,
        hitstunScale: 0.85,
        launchScale: 0.92,
        postureDamageScale: 1,
        backPunishDamageScale: 1,
      },
      defense: {
        damageTakenScale: 1.08,
      },
      guard: {
        impactScale: 1.08,
        blockstunScale: 1.08,
      },
      geometry: {
        weaponLengthScale: 0.94,
      },
    },
    visualProfileId: 'field-cutter-shared',
    materialProfileId: 'raw-steel',
  },
  {
    id: 'field-cutter-heavy',
    familyId: 'field-cutter',
    label: '중량형 현장 절단검',
    shortLabel: '중량형',
    description: '긴 frame · 긴 거리 · 높은 경직',
    goldCost: 120,
    trainingMarkRequirement: 0,
    visualProfile: {
      kind: 'field-cutter',
      source: 'shared-player-weapon',
      materialId: 'raw-steel',
    },
    origin: {
      kind: 'merchant',
    },
    modifiers: {
      combatTiming: {
        startupScale: 1.22,
        recoveryScale: 1.28,
      },
      attack: {
        damageScale: 1.2,
        rangeScale: 1.22,
        hitstunScale: 1.3,
        launchScale: 1.18,
        postureDamageScale: 1,
        backPunishDamageScale: 1,
      },
      defense: {
        damageTakenScale: 0.92,
      },
      guard: {
        impactScale: 0.84,
        blockstunScale: 0.84,
      },
      geometry: {
        weaponLengthScale: 1.18,
      },
    },
    visualProfileId: 'field-cutter-shared',
    materialProfileId: 'raw-steel',
  },
  {
    id: 'field-cutter-swift',
    familyId: 'field-cutter',
    label: '연환형 현장 절단검',
    shortLabel: '연환형',
    description: '가장 짧은 frame · 짧은 reach · 낮은 단발 피해',
    goldCost: 0,
    trainingMarkRequirement: 0,
    visualProfile: {
      kind: 'field-cutter',
      source: 'shared-player-weapon',
      materialId: 'raw-steel',
    },
    origin: {
      kind: 'forge',
      materialId: 'salvaged-drive-core',
      materialCost: 1,
      choiceGroupId: 'scrap-weapon-archetype',
    },
    modifiers: {
      combatTiming: {
        startupScale: 0.68,
        recoveryScale: 0.7,
      },
      attack: {
        damageScale: 0.78,
        rangeScale: 0.84,
        hitstunScale: 0.72,
        launchScale: 1.06,
        postureDamageScale: 0.8,
        backPunishDamageScale: 1,
      },
      defense: {
        damageTakenScale: 1.12,
      },
      guard: {
        impactScale: 1.12,
        blockstunScale: 1.12,
      },
      geometry: {
        weaponLengthScale: 0.88,
      },
    },
    visualProfileId: 'field-cutter-shared',
    materialProfileId: 'raw-steel',
  },
  {
    id: 'field-cutter-breaker',
    familyId: 'field-cutter',
    label: '파쇄형 현장 절단검',
    shortLabel: '파쇄형',
    description: '느린 frame · 강한 guard/posture 파쇄 · 짧은 reach',
    goldCost: 0,
    trainingMarkRequirement: 0,
    visualProfile: {
      kind: 'field-cutter',
      source: 'shared-player-weapon',
      materialId: 'raw-steel',
    },
    origin: {
      kind: 'forge',
      materialId: 'salvaged-drive-core',
      materialCost: 1,
      choiceGroupId: 'scrap-weapon-archetype',
    },
    modifiers: {
      combatTiming: {
        startupScale: 1.18,
        recoveryScale: 1.24,
      },
      attack: {
        damageScale: 1.04,
        rangeScale: 0.94,
        hitstunScale: 1.2,
        launchScale: 0.86,
        postureDamageScale: 1.65,
        backPunishDamageScale: 1,
      },
      defense: {
        damageTakenScale: 0.96,
      },
      guard: {
        impactScale: 0.82,
        blockstunScale: 0.84,
      },
      geometry: {
        weaponLengthScale: 0.98,
      },
    },
    visualProfileId: 'field-cutter-shared',
    materialProfileId: 'raw-steel',
  },
  {
    id: 'field-cutter-reach',
    familyId: 'field-cutter',
    label: '추격형 현장 절단검',
    shortLabel: '추격형',
    description: '가장 긴 reach · 강한 배후 punish · 긴 recovery',
    goldCost: 0,
    trainingMarkRequirement: 0,
    visualProfile: {
      kind: 'field-cutter',
      source: 'shared-player-weapon',
      materialId: 'raw-steel',
    },
    origin: {
      kind: 'forge',
      materialId: 'salvaged-drive-core',
      materialCost: 1,
      choiceGroupId: 'scrap-weapon-archetype',
    },
    modifiers: {
      combatTiming: {
        startupScale: 1.08,
        recoveryScale: 1.18,
      },
      attack: {
        damageScale: 0.88,
        rangeScale: 1.42,
        hitstunScale: 0.9,
        launchScale: 0.9,
        postureDamageScale: 0.85,
        backPunishDamageScale: 1.55,
      },
      defense: {
        damageTakenScale: 1.1,
      },
      guard: {
        impactScale: 1.08,
        blockstunScale: 1.08,
      },
      geometry: {
        weaponLengthScale: 1.36,
      },
    },
    visualProfileId: 'field-cutter-shared',
    materialProfileId: 'raw-steel',
  },
  {
    id: 'field-shield-standard',
    familyId: 'field-shield',
    label: '기본 방호판',
    shortLabel: '기본 방호판',
    description: '낙하물과 압력을 막고 작업 자세를 지지하는 기본 방호판.',
    goldCost: 0,
    trainingMarkRequirement: 0,
    visualProfile: {
      kind: 'field-shield',
      source: 'existing-workwear-placeholder',
      materialId: 'painted-steel',
    },
    origin: {
      kind: 'starter',
    },
    modifiers: {},
    visualProfileId: 'field-shield-shared',
    materialProfileId: 'painted-steel',
  },
  {
    id: 'field-work-helmet',
    familyId: 'helmet',
    label: '작업모',
    shortLabel: '작업모',
    description: '현장 작업용 기본 보호 장비.',
    goldCost: 0,
    trainingMarkRequirement: 0,
    visualProfile: {
      kind: 'workwear-head',
      source: 'existing-workwear-placeholder',
      materialId: 'cloth',
    },
    origin: {
      kind: 'starter',
    },
    modifiers: {},
    setId: 'field-work-set',
    visualProfileId: 'field-work-helmet',
    materialProfileId: 'cloth',
  },
  {
    id: 'field-work-body',
    familyId: 'body-armor',
    label: '작업 덧옷',
    shortLabel: '작업 덧옷',
    description: '현장 작업용 기본 보호 장비.',
    goldCost: 0,
    trainingMarkRequirement: 0,
    visualProfile: {
      kind: 'workwear-body',
      source: 'existing-workwear-placeholder',
      materialId: 'cloth',
    },
    origin: {
      kind: 'starter',
    },
    modifiers: {},
    setId: 'field-work-set',
    visualProfileId: 'field-work-body',
    materialProfileId: 'cloth',
  },
  {
    id: 'field-work-boots',
    familyId: 'boots',
    label: '작업화',
    shortLabel: '작업화',
    description: '현장 작업용 기본 보호 장비.',
    goldCost: 0,
    trainingMarkRequirement: 0,
    visualProfile: {
      kind: 'workwear-boots',
      source: 'existing-workwear-placeholder',
      materialId: 'cloth',
    },
    origin: {
      kind: 'starter',
    },
    modifiers: {},
    setId: 'field-work-set',
    visualProfileId: 'field-work-boots',
    materialProfileId: 'cloth',
  },
  {
    id: 'field-work-lamp',
    familyId: 'tool',
    label: '재사용 작업등',
    shortLabel: '작업등',
    description: '현장 어두운 접속부를 비추는 재사용 작업등.',
    goldCost: 0,
    trainingMarkRequirement: 0,
    visualProfile: {
      kind: 'work-lamp',
      source: 'slot-local-work-lamp',
      materialId: 'painted-steel',
    },
    visualProfileId: 'field-work-lamp',
    materialProfileId: 'painted-steel',
    origin: { kind: 'exploration', id: 'mine-cable-cache' },
    modifiers: {},
  },
]);
