const ENCOUNTER_PROFILES = Object.freeze({
  training: Object.freeze({
    id: 'training',
    role: 'training',
    label: '수거 유닛 모의체',
    presentationProfileId: 'collector-unit',
    respawns: true,
    approachSpeed: 78,
    idleSeconds: 0.3,
    presentationScale: 0.48,
    attackPatterns: Object.freeze([Object.freeze(['light', 'heavy'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({}),
  }),
  'earth-material-echo': Object.freeze({
    id: 'earth-material-echo',
    role: 'material-echo',
    label: '굴착 설비 기생 기계',
    presentationProfileId: 'industrial-creature',
    respawns: true,
    approachSpeed: 74,
    idleSeconds: 0.32,
    presentationScale: 0.46,
    attackPatterns: Object.freeze([Object.freeze(['light', 'heavy'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ earth: 'resistant', lightning: 'weak' }),
    materialReward: Object.freeze({ elementId: 'earth', quantity: 1 }),
  }),
  'fire-material-echo': Object.freeze({
    id: 'fire-material-echo',
    role: 'material-echo',
    label: '과열 수거 유닛',
    presentationProfileId: 'collector-unit',
    respawns: true,
    approachSpeed: 82,
    idleSeconds: 0.28,
    activationRange: 190,
    presentationScale: 0.44,
    attackPatterns: Object.freeze([Object.freeze(['light', 'heavy'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ fire: 'resistant', ice: 'weak' }),
    materialReward: Object.freeze({ elementId: 'fire', quantity: 1 }),
  }),
  'ice-material-echo': Object.freeze({
    id: 'ice-material-echo',
    role: 'material-echo',
    label: '냉각 설비 기생 기계',
    presentationProfileId: 'industrial-creature',
    respawns: true,
    approachSpeed: 68,
    idleSeconds: 0.38,
    activationRange: 180,
    presentationScale: 0.46,
    attackPatterns: Object.freeze([Object.freeze(['light', 'heavy'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ ice: 'resistant', fire: 'weak' }),
    materialReward: Object.freeze({ elementId: 'ice', quantity: 1 }),
  }),
  'glasswind-material-echo': Object.freeze({
    id: 'glasswind-material-echo',
    role: 'material-echo',
    species: 'glasswind',
    label: '풍압 수거 유닛',
    presentationProfileId: 'collector-unit',
    respawns: true,
    approachSpeed: 90,
    idleSeconds: 0.24,
    activationRange: 195,
    presentationScale: 0.47,
    attackPatterns: Object.freeze([Object.freeze(['sweep', 'light', 'sweep'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ lightning: 'resistant', earth: 'weak' }),
    materialReward: Object.freeze({ elementId: 'lightning', quantity: 1 }),
  }),
  field: Object.freeze({
    id: 'field',
    role: 'field',
    label: '설비 기생 기계',
    presentationProfileId: 'industrial-creature',
    respawns: false,
    approachSpeed: 72,
    idleSeconds: 0.36,
    activationRange: 210,
    presentationScale: 0.46,
    attackPatterns: Object.freeze([Object.freeze(['light', 'heavy'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ fire: 'weak', earth: 'resistant' }),
  }),
  'mine-tunnel-collector': Object.freeze({
    id: 'mine-tunnel-collector',
    role: 'field',
    label: '갱도 수거 유닛',
    presentationProfileId: 'collector-unit',
    respawns: false,
    approachSpeed: 82,
    idleSeconds: 0.28,
    activationRange: 230,
    presentationScale: 0.48,
    attackPatterns: Object.freeze([Object.freeze(['light', 'heavy', 'light'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ lightning: 'weak', earth: 'resistant' }),
  }),
  'mine-collapse-boss': Object.freeze({
    id: 'mine-collapse-boss',
    role: 'boss',
    label: '붕괴 광산 굴착기 Boss',
    presentationProfileId: 'mine-collapse-boss',
    respawns: false,
    approachSpeed: 78,
    idleSeconds: 0.25,
    presentationScale: 0.64,
    attackPatterns: Object.freeze([
      Object.freeze(['light', 'heavy', 'light']),
      Object.freeze(['heavy', 'light', 'heavy']),
    ]),
    guardOutsidePunish: true,
    enchantAffinity: Object.freeze({ lightning: 'weak', earth: 'resistant' }),
    posture: Object.freeze({
      maximum: 118,
      groggySeconds: 1.2,
      strongDamage: 50,
      shieldCounterDamage: 66,
    }),
    weakPoint: Object.freeze({
      id: 'mine-walker-drive-shaft',
      label: '노출된 편심 구동축',
      triggerAttackKinds: Object.freeze(['heavy']),
      damageMultiplier: 1.5,
      presentation: Object.freeze({
        offsetX: 0,
        offsetY: -44,
        color: '#f2b34f',
        highlightColor: '#fff1bd',
      }),
    }),
  }),
  boss: Object.freeze({
    id: 'boss',
    role: 'boss',
    label: '지역 산업기계 Boss',
    presentationProfileId: 'regional-boss',
    respawns: false,
    approachSpeed: 86,
    idleSeconds: 0.24,
    presentationScale: 0.58,
    attackPatterns: Object.freeze([
      Object.freeze(['light', 'light', 'heavy']),
      Object.freeze(['light', 'heavy', 'heavy']),
    ]),
    guardOutsidePunish: true,
    enchantAffinity: Object.freeze({ earth: 'weak', fire: 'resistant' }),
    posture: Object.freeze({
      maximum: 100,
      groggySeconds: 1.1,
      strongDamage: 48,
      shieldCounterDamage: 62,
    }),
    weakPoint: Object.freeze({
      id: 'sealed-instructor-core',
      label: '봉인 교관의 흉갑 핵',
      triggerAttackKinds: Object.freeze(['heavy']),
      damageMultiplier: 1.5,
      presentation: Object.freeze({
        offsetX: 0,
        offsetY: -42,
        color: '#63ead5',
        highlightColor: '#effffb',
      }),
    }),
  }),
  'glasswind-field': Object.freeze({
    id: 'glasswind-field',
    role: 'glasswind',
    species: 'glasswind',
    label: '풍식 설비 기생 기계',
    presentationProfileId: 'industrial-creature',
    respawns: false,
    approachSpeed: 94,
    idleSeconds: 0.22,
    activationRange: 235,
    presentationScale: 0.5,
    attackPatterns: Object.freeze([Object.freeze(['sweep', 'light', 'sweep'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ ice: 'weak', lightning: 'resistant' }),
  }),
  'glasswind-boss': Object.freeze({
    id: 'glasswind-boss',
    role: 'boss',
    species: 'glasswind',
    label: '풍압 압착기 Boss',
    presentationProfileId: 'regional-boss',
    respawns: false,
    approachSpeed: 92,
    idleSeconds: 0.2,
    presentationScale: 0.62,
    attackPatterns: Object.freeze([
      Object.freeze(['sweep', 'light', 'heavy']),
      Object.freeze(['sweep', 'heavy', 'sweep']),
    ]),
    guardOutsidePunish: true,
    enchantAffinity: Object.freeze({ lightning: 'weak', ice: 'resistant' }),
    posture: Object.freeze({
      maximum: 120,
      groggySeconds: 1.2,
      strongDamage: 52,
      shieldCounterDamage: 68,
    }),
    weakPoint: Object.freeze({
      id: 'storm-glass-core',
      label: '폭풍 유리핵',
      triggerAttackKinds: Object.freeze(['sweep']),
      damageMultiplier: 1.4,
      presentation: Object.freeze({
        offsetX: 0,
        offsetY: -42,
        color: '#8ff5ef',
        highlightColor: '#ffffff',
      }),
    }),
  }),
});

export { ENCOUNTER_PROFILES };
