const ENCOUNTER_PROFILES = Object.freeze({
  training: Object.freeze({
    id: 'training',
    role: 'training',
    label: '훈련용 마도 골렘',
    respawns: true,
    approachSpeed: 78,
    idleSeconds: 0.3,
    presentationScale: 0.48,
    attackPatterns: Object.freeze([Object.freeze(['light', 'heavy'])]),
    guardOutsidePunish: false,
  }),
  field: Object.freeze({
    id: 'field',
    role: 'field',
    label: '실습림 감시 골렘',
    respawns: false,
    approachSpeed: 72,
    idleSeconds: 0.36,
    activationRange: 210,
    presentationScale: 0.46,
    attackPatterns: Object.freeze([Object.freeze(['light', 'heavy'])]),
    guardOutsidePunish: false,
  }),
  boss: Object.freeze({
    id: 'boss',
    role: 'boss',
    label: '폐쇄 실습림의 봉인 교관',
    respawns: false,
    approachSpeed: 86,
    idleSeconds: 0.24,
    presentationScale: 0.58,
    attackPatterns: Object.freeze([
      Object.freeze(['light', 'light', 'heavy']),
      Object.freeze(['light', 'heavy', 'heavy']),
    ]),
    guardOutsidePunish: true,
    posture: Object.freeze({
      maximum: 100,
      groggySeconds: 1.1,
      strongDamage: 48,
      shieldCounterDamage: 62,
    }),
  }),
  'glasswind-field': Object.freeze({
    id: 'glasswind-field',
    role: 'glasswind',
    species: 'glasswind',
    label: '유리바람 풍식 사냥꾼',
    respawns: false,
    approachSpeed: 94,
    idleSeconds: 0.22,
    activationRange: 235,
    presentationScale: 0.5,
    attackPatterns: Object.freeze([Object.freeze(['sweep', 'light', 'sweep'])]),
    guardOutsidePunish: false,
  }),
  'glasswind-boss': Object.freeze({
    id: 'glasswind-boss',
    role: 'boss',
    species: 'glasswind',
    label: '폭풍 유리핵의 섭정',
    respawns: false,
    approachSpeed: 92,
    idleSeconds: 0.2,
    presentationScale: 0.62,
    attackPatterns: Object.freeze([
      Object.freeze(['sweep', 'light', 'heavy']),
      Object.freeze(['sweep', 'heavy', 'sweep']),
    ]),
    guardOutsidePunish: true,
    posture: Object.freeze({
      maximum: 120,
      groggySeconds: 1.2,
      strongDamage: 52,
      shieldCounterDamage: 68,
    }),
  }),
});

export { ENCOUNTER_PROFILES };
