const ENCOUNTER_PROFILES = Object.freeze({
  'yard-scout-collector': Object.freeze({
    id: 'yard-scout-collector',
    role: 'field',
    species: 'industrial-collector',
    label: '폐병기 소형 수거 유닛',
    presentationProfileId: 'collector-unit',
    respawns: false,
    approachSpeed: 76,
    idleSeconds: 0.32,
    activationRange: 220,
    presentationScale: 0.44,
    attackPatterns: Object.freeze([Object.freeze(['light', 'heavy'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ lightning: 'weak', earth: 'resistant' }),
  }),
  'yard-brace-collector': Object.freeze({
    id: 'yard-brace-collector',
    role: 'field',
    species: 'industrial-collector',
    label: '지지대 회수 유닛',
    presentationProfileId: 'collector-unit',
    respawns: false,
    approachSpeed: 84,
    idleSeconds: 0.27,
    activationRange: 228,
    presentationScale: 0.47,
    attackPatterns: Object.freeze([Object.freeze(['heavy', 'light', 'heavy'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ lightning: 'weak', earth: 'resistant' }),
  }),
  'yard-approach-collector': Object.freeze({
    id: 'yard-approach-collector',
    role: 'field',
    species: 'industrial-collector',
    label: '흉곽 경계 수거 유닛',
    presentationProfileId: 'collector-unit',
    respawns: false,
    approachSpeed: 88,
    idleSeconds: 0.25,
    activationRange: 232,
    presentationScale: 0.49,
    attackPatterns: Object.freeze([Object.freeze(['heavy', 'light', 'heavy', 'light'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ lightning: 'weak', earth: 'resistant' }),
  }),
  'yard-ridge-collector': Object.freeze({
    id: 'yard-ridge-collector',
    role: 'field',
    species: 'industrial-collector',
    label: '흉곽 능선 경계 유닛',
    presentationProfileId: 'collector-unit',
    respawns: false,
    approachSpeed: 90,
    idleSeconds: 0.24,
    activationRange: 234,
    presentationScale: 0.5,
    attackPatterns: Object.freeze([Object.freeze(['heavy', 'heavy', 'light', 'heavy'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ lightning: 'weak', earth: 'resistant' }),
  }),
  'yard-guard-collector': Object.freeze({
    id: 'yard-guard-collector',
    role: 'field',
    species: 'industrial-collector',
    label: '심부 방패 경계 유닛',
    presentationProfileId: 'collector-unit',
    respawns: false,
    approachSpeed: 86,
    idleSeconds: 0.3,
    activationRange: 230,
    presentationScale: 0.5,
    attackPatterns: Object.freeze([Object.freeze(['heavy', 'light', 'heavy'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ lightning: 'weak', earth: 'resistant' }),
  }),
  'mine-tunnel-collector': Object.freeze({
    id: 'mine-tunnel-collector',
    role: 'field',
    label: '갱도 수거 유닛',
    presentationProfileId: 'collector-unit',
    respawns: false,
    approachSpeed: 82,
    idleSeconds: 0.28,
    activationRange: 230,
    presentationScale: 0.48,
    attackPatterns: Object.freeze([Object.freeze(['light', 'heavy', 'light'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ lightning: 'weak', earth: 'resistant' }),
  }),
  'mine-claim-jacker': Object.freeze({
    id: 'mine-claim-jacker',
    role: 'field',
    species: 'human-salvager',
    label: '광산 선점 수거반',
    presentationProfileId: 'mine-claim-jacker',
    respawns: false,
    approachSpeed: 84,
    idleSeconds: 0.27,
    activationRange: 225,
    presentationScale: 0.5,
    completionDisposition: 'surrender',
    attackPatterns: Object.freeze([Object.freeze(['light', 'heavy', 'light'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ earth: 'resistant', lightning: 'weak' }),
  }),
  'mine-seal-plate-raider': Object.freeze({
    id: 'mine-seal-plate-raider',
    role: 'field',
    species: 'human-salvager',
    label: '밀폐 철판 절취 수거반',
    presentationProfileId: 'mine-claim-jacker',
    respawns: false,
    approachSpeed: 87,
    idleSeconds: 0.26,
    activationRange: 236,
    presentationScale: 0.51,
    completionDisposition: 'flee',
    attackPatterns: Object.freeze([Object.freeze(['heavy', 'light', 'heavy'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ earth: 'resistant', lightning: 'weak' }),
  }),
  'mine-collapse-boss': Object.freeze({
    id: 'mine-collapse-boss',
    role: 'boss',
    label: '붕괴 광산 굴착기 Boss',
    presentationProfileId: 'mine-collapse-boss',
    respawns: false,
    approachSpeed: 78,
    idleSeconds: 0.25,
    presentationScale: 0.64,
    attackPatterns: Object.freeze([
      Object.freeze(['light', 'heavy', 'light']),
      Object.freeze(['heavy', 'light', 'heavy']),
    ]),
    guardOutsidePunish: true,
    enchantAffinity: Object.freeze({ lightning: 'weak', earth: 'resistant' }),
    posture: Object.freeze({
      maximum: 118,
      groggySeconds: 1.2,
      strongDamage: 50,
      shieldCounterDamage: 66,
    }),
    weakPoint: Object.freeze({
      id: 'mine-walker-drive-shaft',
      label: '노출된 편심 구동축',
      triggerAttackKinds: Object.freeze(['heavy']),
      damageMultiplier: 1.5,
      presentation: Object.freeze({
        offsetX: 0,
        offsetY: -44,
        color: '#f2b34f',
        highlightColor: '#fff1bd',
      }),
    }),
  }),
  'shipyard-drydock-collector': Object.freeze({
    id: 'shipyard-drydock-collector',
    role: 'field',
    label: '건선거 케이블 수거 유닛',
    presentationProfileId: 'collector-unit',
    respawns: false,
    approachSpeed: 88,
    idleSeconds: 0.24,
    activationRange: 240,
    presentationScale: 0.5,
    attackPatterns: Object.freeze([Object.freeze(['light', 'heavy', 'light'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ lightning: 'weak', ice: 'resistant' }),
  }),
  'dock-salvage-raider': Object.freeze({
    id: 'dock-salvage-raider',
    role: 'field',
    species: 'human-salvager',
    label: '부두 선점 수거반',
    presentationProfileId: 'dock-salvage-raider',
    respawns: false,
    approachSpeed: 90,
    idleSeconds: 0.24,
    activationRange: 240,
    presentationScale: 0.51,
    completionDisposition: 'flee',
    attackPatterns: Object.freeze([Object.freeze(['heavy', 'light', 'heavy'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ ice: 'resistant', lightning: 'weak' }),
  }),
  'shipyard-twin-crane-boss': Object.freeze({
    id: 'shipyard-twin-crane-boss',
    role: 'boss',
    label: '점거된 쌍둥이 크레인 Boss',
    presentationProfileId: 'shipyard-twin-crane-boss',
    respawns: false,
    approachSpeed: 82,
    idleSeconds: 0.22,
    presentationScale: 0.68,
    attackPatterns: Object.freeze([
      Object.freeze(['heavy', 'light', 'heavy']),
      Object.freeze(['light', 'heavy', 'light']),
    ]),
    guardOutsidePunish: true,
    enchantAffinity: Object.freeze({ lightning: 'weak', ice: 'resistant' }),
    posture: Object.freeze({
      maximum: 126,
      groggySeconds: 1.25,
      strongDamage: 52,
      shieldCounterDamage: 68,
    }),
    weakPoint: Object.freeze({
      id: 'shipyard-crane-hydraulic-manifold',
      label: '노출된 쌍둥이 유압 분배기',
      triggerAttackKinds: Object.freeze(['heavy']),
      damageMultiplier: 1.55,
      presentation: Object.freeze({
        offsetX: -18,
        offsetY: -48,
        color: '#59c3c6',
        highlightColor: '#dfffff',
      }),
    }),
  }),
  'greenhouse-pipe-parasite': Object.freeze({
    id: 'greenhouse-pipe-parasite',
    role: 'field',
    label: '지열 배관 기생 기계',
    presentationProfileId: 'industrial-creature',
    respawns: false,
    approachSpeed: 76,
    idleSeconds: 0.3,
    activationRange: 236,
    presentationScale: 0.49,
    attackPatterns: Object.freeze([Object.freeze(['light', 'heavy', 'light'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ ice: 'weak', fire: 'resistant' }),
  }),
  'greenhouse-coolant-parasite': Object.freeze({
    id: 'greenhouse-coolant-parasite',
    role: 'field',
    label: '냉각수 배관 기생 기계',
    presentationProfileId: 'industrial-creature',
    respawns: false,
    approachSpeed: 78,
    idleSeconds: 0.29,
    activationRange: 234,
    presentationScale: 0.48,
    attackPatterns: Object.freeze([Object.freeze(['heavy', 'light', 'heavy'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ ice: 'weak', fire: 'resistant' }),
  }),
  'greenhouse-geothermal-boss': Object.freeze({
    id: 'greenhouse-geothermal-boss',
    role: 'boss',
    label: '과열 지열 조절기 Boss',
    presentationProfileId: 'greenhouse-geothermal-boss',
    respawns: false,
    approachSpeed: 74,
    idleSeconds: 0.26,
    presentationScale: 0.7,
    attackPatterns: Object.freeze([
      Object.freeze(['heavy', 'light', 'heavy']),
      Object.freeze(['light', 'heavy', 'light']),
    ]),
    guardOutsidePunish: true,
    enchantAffinity: Object.freeze({ ice: 'weak', fire: 'resistant' }),
    posture: Object.freeze({
      maximum: 132,
      groggySeconds: 1.3,
      strongDamage: 54,
      shieldCounterDamage: 70,
    }),
    weakPoint: Object.freeze({
      id: 'greenhouse-geothermal-pressure-valve',
      label: '노출된 황동 압력 밸브',
      triggerAttackKinds: Object.freeze(['heavy']),
      damageMultiplier: 1.6,
      presentation: Object.freeze({
        offsetX: 17,
        offsetY: -50,
        color: '#9bd66b',
        highlightColor: '#efffcf',
      }),
    }),
  }),
  'snow-tunnel-collector': Object.freeze({
    id: 'snow-tunnel-collector',
    role: 'field',
    label: '터널 열선 수거 유닛',
    presentationProfileId: 'collector-unit',
    respawns: false,
    approachSpeed: 80,
    idleSeconds: 0.28,
    activationRange: 238,
    presentationScale: 0.5,
    attackPatterns: Object.freeze([Object.freeze(['light', 'heavy', 'light'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ fire: 'weak', ice: 'resistant' }),
  }),
  'snow-route-raider': Object.freeze({
    id: 'snow-route-raider',
    role: 'field',
    species: 'human-salvager',
    label: '설산 길목 수거반',
    presentationProfileId: 'snow-route-raider',
    respawns: false,
    approachSpeed: 86,
    idleSeconds: 0.25,
    activationRange: 238,
    presentationScale: 0.52,
    completionDisposition: 'surrender',
    attackPatterns: Object.freeze([Object.freeze(['light', 'heavy', 'light'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ ice: 'resistant', fire: 'weak' }),
  }),
  'snow-thermal-raider': Object.freeze({
    id: 'snow-thermal-raider',
    role: 'field',
    species: 'human-salvager',
    label: '내한 케이블 절취 수거반',
    presentationProfileId: 'snow-route-raider',
    respawns: false,
    approachSpeed: 88,
    idleSeconds: 0.26,
    activationRange: 236,
    presentationScale: 0.51,
    completionDisposition: 'flee',
    attackPatterns: Object.freeze([Object.freeze(['heavy', 'light', 'heavy'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ ice: 'resistant', fire: 'weak' }),
  }),
  'snowplow-train-boss': Object.freeze({
    id: 'snowplow-train-boss',
    role: 'boss',
    label: '폭주 장갑 제설 열차 Boss',
    presentationProfileId: 'snowplow-train-boss',
    respawns: false,
    approachSpeed: 88,
    idleSeconds: 0.22,
    presentationScale: 0.72,
    attackPatterns: Object.freeze([
      Object.freeze(['heavy', 'light', 'heavy']),
      Object.freeze(['light', 'heavy', 'heavy']),
    ]),
    guardOutsidePunish: true,
    enchantAffinity: Object.freeze({ fire: 'weak', ice: 'resistant' }),
    posture: Object.freeze({
      maximum: 138,
      groggySeconds: 1.35,
      strongDamage: 56,
      shieldCounterDamage: 72,
    }),
    weakPoint: Object.freeze({
      id: 'snowplow-heated-brake-axle',
      label: '노출된 열선 제동축',
      triggerAttackKinds: Object.freeze(['heavy']),
      damageMultiplier: 1.65,
      presentation: Object.freeze({
        offsetX: -19,
        offsetY: -46,
        color: '#b9d7ec',
        highlightColor: '#f4fbff',
      }),
    }),
  }),
  'quarry-cut-collector': Object.freeze({
    id: 'quarry-cut-collector',
    role: 'field',
    label: '발파선 점거 수거 유닛',
    presentationProfileId: 'collector-unit',
    respawns: false,
    approachSpeed: 86,
    idleSeconds: 0.25,
    activationRange: 242,
    presentationScale: 0.51,
    attackPatterns: Object.freeze([Object.freeze(['heavy', 'light', 'heavy'])]),
    guardOutsidePunish: false,
    enchantAffinity: Object.freeze({ lightning: 'weak', earth: 'resistant' }),
  }),
  'quarry-rock-cutter-boss': Object.freeze({
    id: 'quarry-rock-cutter-boss',
    role: 'boss',
    label: '폭주 초대형 암반 절단기 Boss',
    presentationProfileId: 'quarry-rock-cutter-boss',
    respawns: false,
    approachSpeed: 76,
    idleSeconds: 0.24,
    presentationScale: 0.74,
    attackPatterns: Object.freeze([
      Object.freeze(['heavy', 'light', 'heavy']),
      Object.freeze(['light', 'heavy', 'heavy']),
    ]),
    guardOutsidePunish: true,
    enchantAffinity: Object.freeze({ lightning: 'weak', earth: 'resistant' }),
    posture: Object.freeze({
      maximum: 146,
      groggySeconds: 1.4,
      strongDamage: 58,
      shieldCounterDamage: 74,
    }),
    weakPoint: Object.freeze({
      id: 'quarry-cutter-main-bearing',
      label: '노출된 황동 가동 베어링',
      triggerAttackKinds: Object.freeze(['heavy']),
      damageMultiplier: 1.7,
      presentation: Object.freeze({
        offsetX: 20,
        offsetY: -48,
        color: '#d25b43',
        highlightColor: '#ffe2a3',
      }),
    }),
  }),
});

export { ENCOUNTER_PROFILES };
